def on_hit_wall(sprite, location):
    if Xwing.tile_kind_at(TileDirection.RIGHT, assets.tile("""
        myTile1
    """)):
        game.over(True)
    game.over(False)
scene.on_hit_wall(SpriteKind.player, on_hit_wall)

def on_a_pressed():
    Xwing.vy = -100
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def makeGravityCode():
    global PixelToMeters, Gravity, speed
    PixelToMeters = 30
    Gravity = 3 * PixelToMeters
    speed = 1
    Xwing.ay = Gravity
    Xwing.x = speed
    Xwing.vx = 60
def Scene():
    color.set_color(10, color.rgb(43, 44, 54))
    color.set_color(12, color.rgb(70, 71, 87))
    scene.set_background_image(img("""
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccccccccccccccccccc
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccacccccccccccaaaaaaaaaaaac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccacccccccccccaccccccccccac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccacccccccccccaccccccccccac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaccccccac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccaaaaaaaaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaacccccccccccccccccccccacacccccccccccacccaccccccac
        cccccccccccccccccccaaaaaaaaaaaaaaaccccccccccccccccccccccccacccccccccccaccacccccccccccccccaccccaccccccccccccacccacccccccccccccccccccccacacccccccccccacccaccccccac
        cccccccccccccccccccacccccccccccccaccccccccccccccccccccccccacccccccccccaccacccccccccccccccacaaaaaaaaaaccccccacccaccccccccccccccccaaaaaaaaaaaaaccccccacccaccccccac
        cccaaaaaaaaaaaaaaaaaaaaaaccccccccaccccccccccccccccaaaaaaaaaaaaaaccccccaccacccccccccccccccacaccaccaaaaaaaaaaaaaaaaaaaccccccccccccaccccacaccccaccccccacccaccccccac
        cccacccccccccccccccaccccaccccccccaccccaaaaaaaaaaccacccccccaccccaccccccaccacccccccccccccccacaccaccaccaccccccacccacccaccccccccccccaccccacaccccaccccccacccaccccccac
        cccacccccccccccccccaccccaccccccccaccccaccccccccaccacccccccaccccaccccccaccacccccccccccccccacaccaccaaaaaaaaaaaaaaaaaaaccccccccccccaccccacaccccaccccccaaaaaaaaaaaac
        cccacccccccccccaaaaaaaaaaaaccccccaccccaccccccccaccacccccccaccccaccccaaaaaaaaaaaaaccccccccacaccacccccacccccaacccacaccccccccccccccaccccacaccccaccccccccccacccccccc
        cccacccccccccccacccccccccccccccccaaaaaaaaaaaaccaccacccccccaccccaccccacaccaccccccaccccccccacaccacccccacccccaacccacaccccccccccccccaccccacaccccaccccccccccacccccccc
        cccacccccccccccacccccccccccacccccaccccacccccaccaccacccccccaccccaccccacaccaccccccaccccccccacaccacccccacccccaacccacaccccccccccccccaccccacaccccaccccccccaaaaaaaaacc
        cccacccccccccccacccccccccccacccccaccccacccccaccaccacccccccaaaaaaaaaaaaaaaaccccccaccccccaaaaaaaaaaaaaaaaaaaaaaccacaccccccccccccccaccccacaccccaccccccccacacccccacc
        cccacccccccccccacccccccccccaaaaaaaccccacccccaccaccaccccccccccccaccccacacccccccccaccccccacacaccacccccacccccaaaccacaccccccccccccccaccccacaccccaccccccccacacccccacc
        cccaaaaaaaaaaaaacccccccccccacccccaaaaaaaaaaaaccaccaccccccccccccaccccacacccccccccaccccccacacaccacccccacccccaaaccaaaaaaaaaaaaaaaaaaaaaaacaccccaccccccccacacccccacc
        cccaacccccccccaacccccccccccacccaaaaaaaaaaaaaaaaaccaccccccccccaaaaaaaaaaaaaacccccaccccccacacaccaaaaaaaaaaaaaaaaaaaaccccccccccccccacccaacaccccaccccccccacacccccacc
        cccaacccccccccaacccccccccccacccaccccccaccaaaaaaaaaaaaaaaaacccacaccccacaaaaaaaaaaaaaaaaaaaacaaaaaaaaaacccccaaacccaaccccccccccccccacccaaaaaaaaaaaaaaaaaaaacccccacc
        cccaaaaaaaaaaaaacccccccccccacccaccccccaccaccccaaccaccccccacccacaccccacccccacccccaccccccaccccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccaccccccccacccccccacc
        ccccacccccccccaacccccccccccacccaccccccaccaccccaaccaccccccacccacaccccacccccacccccaccccccaccccccccccccccccccacacccaaccccccccccccccacccaccaaaaaaaaaaaaaaacccccccacc
        ccccacccccccccaacccccccccccaaaaaaaaaaaaaaaaaccaaccaccccccacccacaccccacccccacccccaccaaaaaaaaaaaaaaaaaacccccacacccaaccccccccccccccacccaccaccccacccccccaacccccccacc
        ccccacccccccccaaaccccccccccacccaccccacaaaaaaaaaaccaaaaaaaaaaaaaaccccacccccacccccaccacccaccccccccccccacccccacacccaaccccccccccccccacccaccaccccacccccccaacccccccacc
        ccccacccccccccaccaaaaaaaaaaacccaccccaccacacaccaccccccccccacccaccccccacccccacccccaccacccaaaaaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaacccaccaccccacccccccaacccccccacc
        ccccacccccccccacccccccccaccccccaaaaaaaaaaaaaaaaccccccccccacccacccccaaaaaaaaaaaaaaaaaccccccccccccccccacccccacccccaaccccccccccccccacccaccaccccacccccccaacccccccacc
        ccccacccccccccacccccccccacccccccccccaccacacaccccccaaaaaaaaaaaaaaaaaaacccccacccccacaaccccccccccccccccacccccacccccaaccccccccccccccaaaaaaaaaaaaacccccccaacccccccacc
        ccccacccccccccacccccaaaaaaaaaaaaaaacaccacaaaaaaaaaaaaaaaaacccaccccaaaaaaaaaaaaaaacaaccccccccccccccccacccaaaaaaacaaccccccccccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccacccccccccacaccacccaccccccaccccccccccaccccaaccccccacccccccaaccccccccccccccccacccacacccacaaccccccccccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccacccccccccacaccacccaccccccaccccccccccaccccaaccccccacccccccaaccccccccccccccccacccacacccacaaccccccccccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccaaaaaaaaaaaaaaaacccaccccccaccccccccccaaaaaaaaaaaaaacccccccaaccccccccaaaaaaaaaaaaacacccacaaaaaaaaaaaaaaaaaaaaaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccccccccccccacaccccccaccccccacccccccccccccccaaccccccccccccccaaccccccccacccccccacccaaaaaaaaaacccccccaaaaaaaaaaaaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccccccccccccacaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccaaccccccccacccccccaccccaccccacaccccccccaccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccccccccccccacaccccacaccccccacccccccccccccccaacccccaccccccaaaaaaaaaaaaaaaaaaccaccccaccccacaccccccccaccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccaccccccaaaaaaaaaaaaaaacaccccccacccccccccccccccaacccccaccccccacaaccccccccaccccaccaccccaccccacaccccccccacccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaccacc
        ccccacccaaaaaaaaaaaaaaaccccaccccccacacccaacaccccccacccccccccccccccaacccccaccccccacaaccccccccaccccaccaccccaaaaaacaccccccccacccccaacccaccaccccccccccccaaaaaaaaaacc
        ccccacccacccccacccccacaccccaccccccacacccaacaccccccacccccccccccccccaacccccaccccccacaaccccccccaccccaccaccccaccccccaccccccccacccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacacccaacaccccccaaaaaaaaaaaaaaaaaacccccaccccccacaaccccccccaccccaccaccccaccccccaccccccccacccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacacaaaaaaaaaaaaaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccaccccccaccccccccacccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacaaaaaaaaccccccccccccccccccaccccccccccaccccccacccccccccccaccccaccccccaaaaaaaaaaaaaaaaaaaccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacccacaaccccccccccccccccccccaccccccccccaccccccacccccccccccaccccaccccccaaccccccaccccccccaaccccaacccaccaccccccccccccacccccaccccc
        ccccaaaaaaaaaaacccccacaccccaccccccacccacaaccccccccccccccccccccaccccccccccaccccccacccccccccccaaaaaaaaaaaaaaccccccaccccccccaaccccaacccaccaccccccccccccacccccaccccc
        ccccccccacccccccccccacaccccaccccccacccacaaccccccccccccccccccccaccccccccccaccccccaccccccccccccccccaccccccacccccccaccccccccaaccccaacccaccaaaaaaaaaaaaaacccccaccccc
        ccccccccacccccccccccaaaaaaaaaaaaaaacccacaaccccccccccccccccccccaccccaaaaaaaaaaaaaaaaaaccccccccccccaccccccacccccccaaaaaaaaaaaaaaaaacccacccccccccccccccccccccaccccc
        cccaaaaaaaacccccccccccaccccaccccccccccacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccacccaccccccccccccaccccccaccccccccccccccccaaccccaccccacccccccccccccccccccccaccccc
        cccaccccacacccccccccccaccaaaaaaaaaaaaaaaaaaaacccccccccccccccccaccccaccccccccccccacccaccccccccccccaccccccaccccccccccccccccaaccccaccccacccccccccccccccccccccaccccc
        cccaccccacacccccccccccaccacaccccccccccacacccacccccccccccccccccaccccaccccccccccccaccaaaaaaaaaaaccaaaaaaaaaaaaaaaccccccccccaaccccaccccacccccccccccccccccccccaccccc
        cccaccccacacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaaaccccccaccaaccccccccaccaaccccccacccccaccccccccccaaccccacccaaaaaaaaaaaaaaaaaaaccccaccccc
        cccaccccacacccacccccccaccacaaaaaaaaaaaaaacccacccccacccacccacacaccccacccccaccccccaaaaaaaaaaaaaaaaaaccccccacccccaccccccccccaaccccacccaaccccccccccccccccaccccaccccc
        cccaccccacacccacccccccaccaccccccccccccacccccacccccacccacccacacaccccacccccacccccccccaaccccccccaccacccccccacccccaccccccccccaaaaaaaaaaaaccccccccccccccccaccccaccccc
        cccaccccacacaaaaaaacccaccaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccccaccccacccacccccccccccccccccaccccaccccc
        cccaccccacacacacccacccaccaccccccccccccccccccacccccacccacccacaccccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccaaaaaaaaaaaaaaaaaaaaaacccccccaccccaccccc
        cccaccccacacacacccacccaccaccccccccccccccccccacccccacccacccacaccccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccacaccccacccacccccccccacccccccaccccaccccc
        cccaccccacacacacccacccaccaccccccccccccccccccacccccacccaaaaaaaccccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccacaccccacccacccccccccacccccccaccccaccccc
        cccaccccacacacacccacccaccacccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccaaccccccccaccacccccccaaaaaaaaaaaaaaaaaaaccccacccacccccccccacccccccaccccaccccc
        cccaccccaaaaaaaaaaaaaaaccacccccccccccccccccaacccccacccccccaccccccccacccccacccacccccaaccccccccaccacccccccccccccacccccccccaccccccacccacccccccccacccccccaccccaccccc
        cccaccccccacacacccaccccccacccccccccccccccccaacccccacccccccaccccccccacccccacccacccccaaccccccccaccacccccccccccccacccccccccaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccc
        cccaccccccacacacccaccccccacccccccccccccccccaacccccacccccccaaaaaaaaaaaaaaaacccacccccaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccacccccccccacccccccacccccccccc
        cccaccccccacacacccaccccccacccccccccccccccccaacccccaccccccccccccccccacccccccccacccccaacccaccccaccaaaaaaaaaaaaaaacccccccccaccacccccccacccccccccacccccccacccccccccc
        cccaccccccacacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccacccccccccacccccaacccaccccaccccccccaccccccaccccccccccaccacccccccacccccccccacccccccacccccccccc
        cccaccccccacacccccaccccccacccccccccccccccccaaccccccccccccccccccccccacccccccccacccccaaaaaaaaaaaccccccccaccccccaccccccccccaaaaaaaaaaaaaaaaaaaaaacccccccacccccccccc
        cccaccccccacacccccaccccccacccccccccccccccccaaccccccccccccccccccccccaaaaaaaaaaaaaaaaaacccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccccccacacccccaccccccacccccccccccccccccaaccccccccccccccccccccccccccccccccaccccccccccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccaaaaaaaaaaaaaaaccccacccccccccccccccccaaccccccccccccccccccccccccccccccccaccccccccccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccacacacacacccacaccccacccccccccccccccccaaccccccccccccccccccaaaaaaaaaaaaaaaaaaaacccccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccacacacacacccacaccccacccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccacccccacccccccccccccaccccccacccccccccccccacccccccaccccaaaaaaaaaaaaaaaaaacccccc
        cccaccacacacacacccacaccccaccccccccccccccccccaccccccccccccccccccacccccccccccccccccaaaaaaaaaaaaaacccccccaccccccacccccccccccccacccccccaaaaaaaaaaaaaaaaaaacccacccccc
        cccaaaaaaaacacacccacaccccaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccaaaaaaaaaaaaaaaaaaaaaacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccaccccccaccccccccccaacccccccccccacccccccacccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccccaacccccccccccacccccccacccccccccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccccaacccccccccccacccccccacccccccccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccaaaaaacccccccaaaaaaaaaaaaaaaaaaccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccacaacacccccccacacccccccaccccccaccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccacaacacccccccacacccccccaccccccaccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaacacccccccacacccccccaaaaaaaaaaaaaaaaaaaaaaccccccccccccacccccaccccccccccacccccc
        ccccccacacccaaaaaaacacccccccccccccacccacccccccccccccccccccccccccccccccaccccccccacaccaccccaaaaaaaaaaaaccccccccaccccccccccacccccccccccccccacccccaccccccccccacccccc
        ccccccacacccccacacccacccccccccccccacccacccccccccccccccccccccccccccccccaccccccccacaccaccccaccacacccccaccccccccaccccccccccacccccccccccccccacccccaccccccccccacccccc
        ccccccacacccccacacccacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccaccccccccacaccaccccaccacacccccaccccccccaccccccccccacccccccccccccccaaaaaaaaaaaaaaaaaacccccc
        ccccccacacccccacacccacacccccccccacaaccacccccccaaaaaaaaaaaaaaacccccccccaccccccccacaaaaaaaaaaaaaacccccaccccccccaccccccccccacccccccccccccccccccccaccccccccccccccccc
        ccccccacaaaaaaaaaaaaacacccccccccacaaccacccccccaccccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccccccaccccccccccacccccccccccccccccccccaccccccccccccccccc
        ccccccacccccccacacccccacccccccccacaaccacccccccaccccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccaaaaaaaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaaccccccccc
        ccccccacccccccacacccccacccccccccacaaccacccccccaccccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        ccccccacccccccacaaaaaaaaaaaaaaaaaaaaccacccccccacaaaaaaaaaaaaaaaaaaaaaaaccccccccaccccaccccaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        ccccccacccccccacccccccacccccccccaccaccacccccccacaccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        cccaaaaaaaaaaaaaaaccccacccccccccaccaccacccccccacaccaccccccccaccccccaaaaaaaaaaaaaaaaaaaaacaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        cccaccacccccccaccaccccacccccccccaccaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccaccccaccacaccacccccccaccccacccaccccccccccaaaaaaaaaaaaaaaaaaaaaaacccccccaccccccccc
        cccaccacccccccaccaccccacccccccccaccaccccccccccacaccaccccccccaccccccaccaccccccccaccccaccacaccaaaaaaaaaaaaaaaaaacccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccaaaaaaaaccacccccccccaccaccccccccccacaccaccccccccaccccccaccaccccccccaaaaaaccacaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccaccccccccaccccccaccacccccccccccccaccacaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccaccccccccaccccccaaaaaaaaaaaaaaaaaaaaacaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccaccccccccacccccccccaccccccccccccccccccaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccacccccccccaccccccccccccccccccaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaccccccaaaaaaaaaaaaaaaaaaaacccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccccccaccccaccccccaccaccaccccccccccaaaaaaaaaaacacccaccccacccccccccacccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccccccaccccaccccccaccaccaccccccccccacaccaccccacacccaccccacccccccccacccccccccccacccccaccccccccccaaaaaaaaaaaaaccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaaaaaaaaaaaaaaaaaaaaaaaccaccccccccccacaccaccccacacccaccccacccccccccacccccccccccacccccaccccccccccacccccacccccaccc
        cccaaaaaaaaaacaaaacaccacccccccccaccaccccccccccaccccccccaccccaccccccacccccaccccccccccacaccaccccacacccaccccacccccccccacccccccccccacccccaccccccccccacccccacccccaccc
        ccccccacccccacaccccaccaaaaaaaaaaaaaaaaaaaaaaacaccccccccaccccaccccccacccccaccccccccccacaccaaaaaaaaaaaaccccacccccccccaccccccaaaaaaaaaaaaaaaaaaccccacccccacccccaccc
        ccccccacccccacaaaaaaaaaaaaaaaaaaaccaccccccccacaccccccccaccccaccccccacccccaccccccccccacacccccccacaccccccccacccccccccaccccccaccccacccccaaaaaaaaaaaaaaaaaacccccaccc
        ccccccacccccacaccccaccaccccccccccccaccccccccacaccccccccaccccaccccccacccccaccccccccccacacccccccacaccccccccaaaaaaaaaaaaaaaaaaaaaaacccccccccccaccccacccccccccccaccc
        ccccccaaaaaaaaaccccaccaccccccccccccaccccccccacaaaaaaaaaaaaaaaccccccaaaaaaaaaaaaaaaaaaaacccccccacaccccccccccccccccccaccccccaccccccccccccccccaccccacccccccccccaccc
        ccccccccccccaccccccaccaccccccccccccaccccccccaccccccccccacccccccccccccccccaccccccccccacccccccccacaccccccccccccccccccaccccccaccccccccccccccccaccccacccccccccccaccc
        ccccccccccccaccccccaccaaaaaaaaaaaaaaccccccccaccccccccccacccccccccccccccccaccccccccccacccccccccacaccccccccccccccccccaccccccaccccccccccccccccaccccacccccccccccaccc
        ccccccccccccaccccccaccacccccccccccccccccccccaccccccccccacccccccccccccccccacccccccaaaaaaaaaccaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaaacccccccccccaccccacccccccccccaccc
        cccccaaaaaaaaaaaaacaccacccccccccccccccccccccaccccccccccacccccccccccccccccacccccccaccaccccaccacacaaaaaaaaaaaaaaaaaaaaccccccaccccacccccccccccaccccacccccccccccaccc
        cccccaccccccaccccacaccacccccccccccccccccccaaaaaaaaaaaaaaaaaaaacccccccccccacccccccaccaaaaaaaaaaaccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccaccccccaaaaaaaaccacccccccccccccccccccacaccccccccccacccccaccaaaaaaaaaaaaaaaaaaaacccccaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccacccccaccaccccccccacccccccacacccccaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccacccccaccaccccccccacccccccacacccccaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccaaaaaaaaaaaaaaaaaaacccccccaaaaaaaaaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccaaaaaaaaaaaaaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccccccccaccaccccccccccccccccccaccccccccaccccccccccacccccaccccccccccccaccccacccccccccccacccccccccccccccccccc
        cccccaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccaccaccccccccccccccccccaccccccccaccccccccccacccccaccccccccccccaaaaaaaaaaaaaaaaaacccccccccccccccccccc
        ccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaccccccccaccccccccccacccccacccccccccccccccccacccccccccccccccccccccccccccccccc
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaacccccacccccccccccccccccacccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaacccccccccccccccccccccccccccccccc
    """))
    tiles.set_current_tilemap(tilemap("""
        level1
    """))
    scene.center_camera_at(0, 0)
    scene.camera_follow_sprite(Xwing)

def on_a_released():
    Xwing.vy = 16
controller.A.on_event(ControllerButtonEvent.RELEASED, on_a_released)

speed = 0
Gravity = 0
PixelToMeters = 0
Xwing: Sprite = None
color.set_color(11, color.rgb(122, 122, 122))
color.set_color(15, color.rgb(20, 20, 20))
Xwing = sprites.create(img("""
        ................................
            .............11111111111b.......
            ...........1111111111111bbb.....
            .....22bbb1ff11111..............
            ...2244bbb1fff....11111bbb......
            ..2245bbbb11111666....1b........
            ....222...b11116666111..........
            .........b11111111111111........
            .........b11111111114441144.....
            ....22....b11111111111111111....
            ..2245bbbbb1111......bbb........
            ...2444bbb1111....11111bbb......
            ....222bbb11111111..............
            ...........1111111111111bbb.....
            .............11111111111b.......
            ................................
    """),
    SpriteKind.player)
scene.camera_follow_sprite(Xwing)
Scene()
makeGravityCode()

def on_update_interval():
    Xwing.x += speed
game.on_update_interval(100, on_update_interval)

def on_update_interval2():
    if Xwing.tile_kind_at(TileDirection.RIGHT, assets.tile("""
        myTile4
    """)):
        info.change_score_by(1)
game.on_update_interval(214, on_update_interval2)
