scene.onHitWall(SpriteKind.Player, function (sprite, location) {
    game.over(false)
    if (Xwing.tileKindAt(TileDirection.Right, assets.tile`myTile1`)) {
        game.over(true)
    }
})
function makeGravityCode () {
    PixelToMeters = 30
    Gravity = 3 * PixelToMeters
    Xwing.ay = Gravity
}
function Scene () {
    color.setColor(10, color.rgb(43, 44, 54))
    color.setColor(12, color.rgb(70, 71, 87))
    scene.setBackgroundImage(img`
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccccccccccccccccccc
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccacccccccccccaaaaaaaaaaaac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccacccccccccccaccccccccccac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccacccccccccccaccccccccccac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccacccccccccccccccccccccccccccccccccacccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaccccccac
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccaaaaaaaaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaacccccccccccccccccccccacacccccccccccacccaccccccac
        cccccccccccccccccccaaaaaaaaaaaaaaaccccccccccccccccccccccccacccccccccccaccacccccccccccccccaccccaccccccccccccacccacccccccccccccccccccccacacccccccccccacccaccccccac
        cccccccccccccccccccacccccccccccccaccccccccccccccccccccccccacccccccccccaccacccccccccccccccacaaaaaaaaaaccccccacccaccccccccccccccccaaaaaaaaaaaaaccccccacccaccccccac
        cccaaaaaaaaaaaaaaaaaaaaaaccccccccaccccccccccccccccaaaaaaaaaaaaaaccccccaccacccccccccccccccacaccaccaaaaaaaaaaaaaaaaaaaccccccccccccaccccacaccccaccccccacccaccccccac
        cccacccccccccccccccaccccaccccccccaccccaaaaaaaaaaccacccccccaccccaccccccaccacccccccccccccccacaccaccaccaccccccacccacccaccccccccccccaccccacaccccaccccccacccaccccccac
        cccacccccccccccccccaccccaccccccccaccccaccccccccaccacccccccaccccaccccccaccacccccccccccccccacaccaccaaaaaaaaaaaaaaaaaaaccccccccccccaccccacaccccaccccccaaaaaaaaaaaac
        cccacccccccccccaaaaaaaaaaaaccccccaccccaccccccccaccacccccccaccccaccccaaaaaaaaaaaaaccccccccacaccacccccacccccaacccacaccccccccccccccaccccacaccccaccccccccccacccccccc
        cccacccccccccccacccccccccccccccccaaaaaaaaaaaaccaccacccccccaccccaccccacaccaccccccaccccccccacaccacccccacccccaacccacaccccccccccccccaccccacaccccaccccccccccacccccccc
        cccacccccccccccacccccccccccacccccaccccacccccaccaccacccccccaccccaccccacaccaccccccaccccccccacaccacccccacccccaacccacaccccccccccccccaccccacaccccaccccccccaaaaaaaaacc
        cccacccccccccccacccccccccccacccccaccccacccccaccaccacccccccaaaaaaaaaaaaaaaaccccccaccccccaaaaaaaaaaaaaaaaaaaaaaccacaccccccccccccccaccccacaccccaccccccccacacccccacc
        cccacccccccccccacccccccccccaaaaaaaccccacccccaccaccaccccccccccccaccccacacccccccccaccccccacacaccacccccacccccaaaccacaccccccccccccccaccccacaccccaccccccccacacccccacc
        cccaaaaaaaaaaaaacccccccccccacccccaaaaaaaaaaaaccaccaccccccccccccaccccacacccccccccaccccccacacaccacccccacccccaaaccaaaaaaaaaaaaaaaaaaaaaaacaccccaccccccccacacccccacc
        cccaacccccccccaacccccccccccacccaaaaaaaaaaaaaaaaaccaccccccccccaaaaaaaaaaaaaacccccaccccccacacaccaaaaaaaaaaaaaaaaaaaaccccccccccccccacccaacaccccaccccccccacacccccacc
        cccaacccccccccaacccccccccccacccaccccccaccaaaaaaaaaaaaaaaaacccacaccccacaaaaaaaaaaaaaaaaaaaacaaaaaaaaaacccccaaacccaaccccccccccccccacccaaaaaaaaaaaaaaaaaaaacccccacc
        cccaaaaaaaaaaaaacccccccccccacccaccccccaccaccccaaccaccccccacccacaccccacccccacccccaccccccaccccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccaccccccccacccccccacc
        ccccacccccccccaacccccccccccacccaccccccaccaccccaaccaccccccacccacaccccacccccacccccaccccccaccccccccccccccccccacacccaaccccccccccccccacccaccaaaaaaaaaaaaaaacccccccacc
        ccccacccccccccaacccccccccccaaaaaaaaaaaaaaaaaccaaccaccccccacccacaccccacccccacccccaccaaaaaaaaaaaaaaaaaacccccacacccaaccccccccccccccacccaccaccccacccccccaacccccccacc
        ccccacccccccccaaaccccccccccacccaccccacaaaaaaaaaaccaaaaaaaaaaaaaaccccacccccacccccaccacccaccccccccccccacccccacacccaaccccccccccccccacccaccaccccacccccccaacccccccacc
        ccccacccccccccaccaaaaaaaaaaacccaccccaccacacaccaccccccccccacccaccccccacccccacccccaccacccaaaaaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaacccaccaccccacccccccaacccccccacc
        ccccacccccccccacccccccccaccccccaaaaaaaaaaaaaaaaccccccccccacccacccccaaaaaaaaaaaaaaaaaccccccccccccccccacccccacccccaaccccccccccccccacccaccaccccacccccccaacccccccacc
        ccccacccccccccacccccccccacccccccccccaccacacaccccccaaaaaaaaaaaaaaaaaaacccccacccccacaaccccccccccccccccacccccacccccaaccccccccccccccaaaaaaaaaaaaacccccccaacccccccacc
        ccccacccccccccacccccaaaaaaaaaaaaaaacaccacaaaaaaaaaaaaaaaaacccaccccaaaaaaaaaaaaaaacaaccccccccccccccccacccaaaaaaacaaccccccccccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccacccccccccacaccacccaccccccaccccccccccaccccaaccccccacccccccaaccccccccccccccccacccacacccacaaccccccccccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccacccccccccacaccacccaccccccaccccccccccaccccaaccccccacccccccaaccccccccccccccccacccacacccacaaccccccccccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccaaaaaaaaaaaaaaaacccaccccccaccccccccccaaaaaaaaaaaaaacccccccaaccccccccaaaaaaaaaaaaacacccacaaaaaaaaaaaaaaaaaaaaaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccccccccccccacaccccccaccccccacccccccccccccccaaccccccccccccccaaccccccccacccccccacccaaaaaaaaaacccccccaaaaaaaaaaaaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccccccccccccacaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccaaccccccccacccccccaccccaccccacaccccccccaccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccacccccccccccccacaccccacaccccccacccccccccccccccaacccccaccccccaaaaaaaaaaaaaaaaaaccaccccaccccacaccccccccaccccccacccaccaccccccccccccaacccccccacc
        ccccacccccccccacccccaccccccaaaaaaaaaaaaaaacaccccccacccccccccccccccaacccccaccccccacaaccccccccaccccaccaccccaccccacaccccccccacccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaccacc
        ccccacccaaaaaaaaaaaaaaaccccaccccccacacccaacaccccccacccccccccccccccaacccccaccccccacaaccccccccaccccaccaccccaaaaaacaccccccccacccccaacccaccaccccccccccccaaaaaaaaaacc
        ccccacccacccccacccccacaccccaccccccacacccaacaccccccacccccccccccccccaacccccaccccccacaaccccccccaccccaccaccccaccccccaccccccccacccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacacccaacaccccccaaaaaaaaaaaaaaaaaacccccaccccccacaaccccccccaccccaccaccccaccccccaccccccccacccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacacaaaaaaaaaaaaaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccaccccccaccccccccacccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacaaaaaaaaccccccccccccccccccaccccccccccaccccccacccccccccccaccccaccccccaaaaaaaaaaaaaaaaaaaccccaacccaccaccccccccccccacccccaccccc
        ccccacccacccccacccccacaccccaccccccacccacaaccccccccccccccccccccaccccccccccaccccccacccccccccccaccccaccccccaaccccccaccccccccaaccccaacccaccaccccccccccccacccccaccccc
        ccccaaaaaaaaaaacccccacaccccaccccccacccacaaccccccccccccccccccccaccccccccccaccccccacccccccccccaaaaaaaaaaaaaaccccccaccccccccaaccccaacccaccaccccccccccccacccccaccccc
        ccccccccacccccccccccacaccccaccccccacccacaaccccccccccccccccccccaccccccccccaccccccaccccccccccccccccaccccccacccccccaccccccccaaccccaacccaccaaaaaaaaaaaaaacccccaccccc
        ccccccccacccccccccccaaaaaaaaaaaaaaacccacaaccccccccccccccccccccaccccaaaaaaaaaaaaaaaaaaccccccccccccaccccccacccccccaaaaaaaaaaaaaaaaacccacccccccccccccccccccccaccccc
        cccaaaaaaaacccccccccccaccccaccccccccccacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccacccaccccccccccccaccccccaccccccccccccccccaaccccaccccacccccccccccccccccccccaccccc
        cccaccccacacccccccccccaccaaaaaaaaaaaaaaaaaaaacccccccccccccccccaccccaccccccccccccacccaccccccccccccaccccccaccccccccccccccccaaccccaccccacccccccccccccccccccccaccccc
        cccaccccacacccccccccccaccacaccccccccccacacccacccccccccccccccccaccccaccccccccccccaccaaaaaaaaaaaccaaaaaaaaaaaaaaaccccccccccaaccccaccccacccccccccccccccccccccaccccc
        cccaccccacacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaaaccccccaccaaccccccccaccaaccccccacccccaccccccccccaaccccacccaaaaaaaaaaaaaaaaaaaccccaccccc
        cccaccccacacccacccccccaccacaaaaaaaaaaaaaacccacccccacccacccacacaccccacccccaccccccaaaaaaaaaaaaaaaaaaccccccacccccaccccccccccaaccccacccaaccccccccccccccccaccccaccccc
        cccaccccacacccacccccccaccaccccccccccccacccccacccccacccacccacacaccccacccccacccccccccaaccccccccaccacccccccacccccaccccccccccaaaaaaaaaaaaccccccccccccccccaccccaccccc
        cccaccccacacaaaaaaacccaccaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccccaccccacccacccccccccccccccccaccccaccccc
        cccaccccacacacacccacccaccaccccccccccccccccccacccccacccacccacaccccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccaaaaaaaaaaaaaaaaaaaaaacccccccaccccaccccc
        cccaccccacacacacccacccaccaccccccccccccccccccacccccacccacccacaccccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccacaccccacccacccccccccacccccccaccccaccccc
        cccaccccacacacacccacccaccaccccccccccccccccccacccccacccaaaaaaaccccccacccccacccccccccaaccccccccaccacccccccacccccacccccccccacaccccacccacccccccccacccccccaccccaccccc
        cccaccccacacacacccacccaccacccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccaaccccccccaccacccccccaaaaaaaaaaaaaaaaaaaccccacccacccccccccacccccccaccccaccccc
        cccaccccaaaaaaaaaaaaaaaccacccccccccccccccccaacccccacccccccaccccccccacccccacccacccccaaccccccccaccacccccccccccccacccccccccaccccccacccacccccccccacccccccaccccaccccc
        cccaccccccacacacccaccccccacccccccccccccccccaacccccacccccccaccccccccacccccacccacccccaaccccccccaccacccccccccccccacccccccccaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccc
        cccaccccccacacacccaccccccacccccccccccccccccaacccccacccccccaaaaaaaaaaaaaaaacccacccccaacccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacccccccacccccccccacccccccacccccccccc
        cccaccccccacacacccaccccccacccccccccccccccccaacccccaccccccccccccccccacccccccccacccccaacccaccccaccaaaaaaaaaaaaaaacccccccccaccacccccccacccccccccacccccccacccccccccc
        cccaccccccacacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccacccccccccacccccaacccaccccaccccccccaccccccaccccccccccaccacccccccacccccccccacccccccacccccccccc
        cccaccccccacacccccaccccccacccccccccccccccccaaccccccccccccccccccccccacccccccccacccccaaaaaaaaaaaccccccccaccccccaccccccccccaaaaaaaaaaaaaaaaaaaaaacccccccacccccccccc
        cccaccccccacacccccaccccccacccccccccccccccccaaccccccccccccccccccccccaaaaaaaaaaaaaaaaaacccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccccccacacccccaccccccacccccccccccccccccaaccccccccccccccccccccccccccccccccaccccccccccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccaaaaaaaaaaaaaaaccccacccccccccccccccccaaccccccccccccccccccccccccccccccccaccccccccccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccacacacacacccacaccccacccccccccccccccccaaccccccccccccccccccaaaaaaaaaaaaaaaaaaaacccccacccccccccccccaccccccacccccccccccccacccccccacccccccccccccccccacccccccccc
        cccaccacacacacacccacaccccacccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccacccccacccccccccccccaccccccacccccccccccccacccccccaccccaaaaaaaaaaaaaaaaaacccccc
        cccaccacacacacacccacaccccaccccccccccccccccccaccccccccccccccccccacccccccccccccccccaaaaaaaaaaaaaacccccccaccccccacccccccccccccacccccccaaaaaaaaaaaaaaaaaaacccacccccc
        cccaaaaaaaacacacccacaccccaccccccccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccacccccacccccccaccccccacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacccacaccccaccccccccccccacccccaccccccccccccccccccaccccccaccccccccccaacccccaaaaaaaaaaaaaaaaaaaaaacccccccccccccaccccccccccccaccccccccccccccccacccccc
        ccccccacacccacacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccaccccccaccccccccccaacccccccccccacccccccacccccccccccccccccaaaaaaaaaaaaaaaaaaaaaaaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccccaacccccccccccacccccccacccccccccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccccaacccccccccccacccccccacccccccccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccaaaaaacccccccaaaaaaaaaaaaaaaaaaccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccacaacacccccccacacccccccaccccccaccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaccccccaccccccccacaacacccccccacacccccccaccccccaccccccccccaccaccccccccccccacccccaccccccccccacccccc
        ccccccacacccacacacacacccccccccccccacccaccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaacacccccccacacccccccaaaaaaaaaaaaaaaaaaaaaaccccccccccccacccccaccccccccccacccccc
        ccccccacacccaaaaaaacacccccccccccccacccacccccccccccccccccccccccccccccccaccccccccacaccaccccaaaaaaaaaaaaccccccccaccccccccccacccccccccccccccacccccaccccccccccacccccc
        ccccccacacccccacacccacccccccccccccacccacccccccccccccccccccccccccccccccaccccccccacaccaccccaccacacccccaccccccccaccccccccccacccccccccccccccacccccaccccccccccacccccc
        ccccccacacccccacacccacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccaccccccccacaccaccccaccacacccccaccccccccaccccccccccacccccccccccccccaaaaaaaaaaaaaaaaaacccccc
        ccccccacacccccacacccacacccccccccacaaccacccccccaaaaaaaaaaaaaaacccccccccaccccccccacaaaaaaaaaaaaaacccccaccccccccaccccccccccacccccccccccccccccccccaccccccccccccccccc
        ccccccacaaaaaaaaaaaaacacccccccccacaaccacccccccaccccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccccccaccccccccccacccccccccccccccccccccaccccccccccccccccc
        ccccccacccccccacacccccacccccccccacaaccacccccccaccccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccaaaaaaaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaaccccccccc
        ccccccacccccccacacccccacccccccccacaaccacccccccaccccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        ccccccacccccccacaaaaaaaaaaaaaaaaaaaaccacccccccacaaaaaaaaaaaaaaaaaaaaaaaccccccccaccccaccccaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        ccccccacccccccacccccccacccccccccaccaccacccccccacaccaccccccccacccccccccaccccccccaccccaccccaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        cccaaaaaaaaaaaaaaaccccacccccccccaccaccacccccccacaccaccccccccaccccccaaaaaaaaaaaaaaaaaaaaacaccacccccccaccccacccaccccccccccaccccccacccccaccccccccacccccccaccccccccc
        cccaccacccccccaccaccccacccccccccaccaccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccaccccaccacaccacccccccaccccacccaccccccccccaaaaaaaaaaaaaaaaaaaaaaacccccccaccccccccc
        cccaccacccccccaccaccccacccccccccaccaccccccccccacaccaccccccccaccccccaccaccccccccaccccaccacaccaaaaaaaaaaaaaaaaaacccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccaaaaaaaaccacccccccccaccaccccccccccacaccaccccccccaccccccaccaccccccccaaaaaaccacaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccaccccccccaccccccaccacccccccccccccaccacaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccaccccccccaccccccaaaaaaaaaaaaaaaaaaaaacaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccaccccccccacccccccccaccccccccccccccccccaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccccccacccccccccaccccccccccccccccccaccccccccccaccccacccccccccccccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccccccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccaccccccaaaaaaaaaaaaaaaaaaaacccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccccccaccccaccccccaccaccaccccccccccaaaaaaaaaaacacccaccccacccccccccacccccccccccacccccaccccccccccccccccaccccccccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaccccccaccccaccccccaccaccaccccccccccacaccaccccacacccaccccacccccccccacccccccccccacccccaccccccccccaaaaaaaaaaaaaccc
        cccaccacccccacaccacaccacccccccccaccaccccccccccacaaaaaaaaaaaaaaaaaaaaaaaccaccccccccccacaccaccccacacccaccccacccccccccacccccccccccacccccaccccccccccacccccacccccaccc
        cccaaaaaaaaaacaaaacaccacccccccccaccaccccccccccaccccccccaccccaccccccacccccaccccccccccacaccaccccacacccaccccacccccccccacccccccccccacccccaccccccccccacccccacccccaccc
        ccccccacccccacaccccaccaaaaaaaaaaaaaaaaaaaaaaacaccccccccaccccaccccccacccccaccccccccccacaccaaaaaaaaaaaaccccacccccccccaccccccaaaaaaaaaaaaaaaaaaccccacccccacccccaccc
        ccccccacccccacaaaaaaaaaaaaaaaaaaaccaccccccccacaccccccccaccccaccccccacccccaccccccccccacacccccccacaccccccccacccccccccaccccccaccccacccccaaaaaaaaaaaaaaaaaacccccaccc
        ccccccacccccacaccccaccaccccccccccccaccccccccacaccccccccaccccaccccccacccccaccccccccccacacccccccacaccccccccaaaaaaaaaaaaaaaaaaaaaaacccccccccccaccccacccccccccccaccc
        ccccccaaaaaaaaaccccaccaccccccccccccaccccccccacaaaaaaaaaaaaaaaccccccaaaaaaaaaaaaaaaaaaaacccccccacaccccccccccccccccccaccccccaccccccccccccccccaccccacccccccccccaccc
        ccccccccccccaccccccaccaccccccccccccaccccccccaccccccccccacccccccccccccccccaccccccccccacccccccccacaccccccccccccccccccaccccccaccccccccccccccccaccccacccccccccccaccc
        ccccccccccccaccccccaccaaaaaaaaaaaaaaccccccccaccccccccccacccccccccccccccccaccccccccccacccccccccacaccccccccccccccccccaccccccaccccccccccccccccaccccacccccccccccaccc
        ccccccccccccaccccccaccacccccccccccccccccccccaccccccccccacccccccccccccccccacccccccaaaaaaaaaccaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaaacccccccccccaccccacccccccccccaccc
        cccccaaaaaaaaaaaaacaccacccccccccccccccccccccaccccccccccacccccccccccccccccacccccccaccaccccaccacacaaaaaaaaaaaaaaaaaaaaccccccaccccacccccccccccaccccacccccccccccaccc
        cccccaccccccaccccacaccacccccccccccccccccccaaaaaaaaaaaaaaaaaaaacccccccccccacccccccaccaaaaaaaaaaaccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccaccccccaaaaaaaaccacccccccccccccccccccacaccccccccccacccccaccaaaaaaaaaaaaaaaaaaaacccccaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccacccccaccaccccccccacccccccacacccccaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccacccccaccaccccccccacccccccacacccccaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccacccccccccccaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccaaaaaaaaaaaaaaaaaaacccccccaaaaaaaaaccaccccccccccacccccaccccccccccccaccccacccccccccccaccccaaaaaaaaaaaaaccc
        cccccacccccccccccaccccacccccccccccccccccccacaccccccccccccccccaccaccccccccccccccccccaccccccccaccccccccccacccccaccccccccccccaccccacccccccccccacccccccccccccccccccc
        cccccaaaaaaaaaaaaaccccaaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccaccaccccccccccccccccccaccccccccaccccccccccacccccaccccccccccccaaaaaaaaaaaaaaaaaacccccccccccccccccccc
        ccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaaaccaaaaaaaaaaaaaaaaaaaaccccccccaccccccccccacccccacccccccccccccccccacccccccccccccccccccccccccccccccc
        ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaacccccacccccccccccccccccacccccccccccccccccccccccccccccccc
        cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaaaaaaaaaaaaaaacccccccccccccccccccccccccccccccc
        `)
    tiles.setCurrentTilemap(tilemap`level1`)
    scene.centerCameraAt(0, 0)
    scene.cameraFollowSprite(Xwing)
}
let Gravity = 0
let PixelToMeters = 0
let Xwing: Sprite = null
color.setColor(11, color.rgb(122, 122, 122))
color.setColor(15, color.rgb(20, 20, 20))
Xwing = sprites.create(img`
    ................................
    .............11111111111b.......
    ...........1111111111111bbb.....
    .....22bbb1ff11111..............
    ...2244bbb1fff....11111bbb......
    ..2245bbbb11111666....1b........
    ....222...b11116666111..........
    .........b11111111111111........
    .........b11111111114441144.....
    ....22....b11111111111111111....
    ..2245bbbbb1111......bbb........
    ...2444bbb1111....11111bbb......
    ....222bbb11111111..............
    ...........1111111111111bbb.....
    .............11111111111b.......
    ................................
    `, SpriteKind.Player)
controller.moveSprite(Xwing, 0, 100)
scene.cameraFollowSprite(Xwing)
Scene()
makeGravityCode()
game.onUpdateInterval(300, function () {
    Xwing.vx += 1
})
